<a href="https://colab.research.google.com/github/RonakkudalAI/Data-Analysis/blob/main/Factor_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = {
    "Math":[85,78,92,70,88],
    "Physics":[80,75,89,65,84],
    "Chemistry":[82,77,90,68,86],
    "English":[60,65,58,70,62],
    "History":[55,60,52,68,57]
}
df = pd.DataFrame(data)
df

,Math,Physics,Chemistry,English,History
0,85,80,82,60,55
1,78,75,77,65,60
2,92,89,90,58,52
3,70,65,68,70,68
4,88,84,86,62,57


In [ ]:
arr = df.to_numpy()
print(arr)

[[85 80 82 60 55]
 [78 75 77 65 60]
 [92 89 90 58 52]
 [70 65 68 70 68]
 [88 84 86 62 57]]


In [ ]:
eigen_values, eigen_vectors = np.linalg.eig(arr)
print(eigen_values)

[ 3.63480087e+02  1.11818145e+01 -3.24355469e-01  8.09933104e-01
  1.85252043e+00]


In [ ]:
print(eigen_vectors)

[[-0.4454721   0.1814659  -0.11682039  0.5608381   0.48655769]
 [-0.43658319 -0.27933623 -0.60777329 -0.04718011 -0.66237259]
 [-0.46904907  0.51685423  0.71665908 -0.58966411  0.27003022]
 [-0.41913078 -0.75767055  0.21564376  0.43375223 -0.41644876]
 [-0.46397423  0.21872002 -0.23845787 -0.38391392  0.27960379]]


In [ ]:
for i in range(len(eigen_values)):

    if eigen_values[i] > 1:
        print("Eigen Value:", eigen_values[i])
        print("Corresponding Eigen Vector:", eigen_vectors[:, i])
        print("----------------------------")

Eigen Value: 363.48008748147333
Corresponding Eigen Vector: [-0.4454721  -0.43658319 -0.46904907 -0.41913078 -0.46397423]
----------------------------
Eigen Value: 11.181814450305488
Corresponding Eigen Vector: [ 0.1814659  -0.27933623  0.51685423 -0.75767055  0.21872002]
----------------------------
Eigen Value: 1.8525204335105527
Corresponding Eigen Vector: [ 0.48655769 -0.66237259  0.27003022 -0.41644876  0.27960379]
----------------------------


In [ ]:
from sklearn.decomposition import FactorAnalysis


In [ ]:
#Model Create
fa = FactorAnalysis(n_components=2)

# Fit + Transform
factors = fa.fit_transform(df)

print(factors)

[[-0.20733296  1.69808917]
 [ 0.47087717 -0.00983775]
 [-1.23450111  0.03523055]
 [ 1.65586629 -0.33332309]
 [-0.68490938 -1.39015887]]
